name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install minimal deps (CPU)
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn lightgbm opencv-python-headless matplotlib pytest ruff
          # ultralytics pulls torch; install CPU torch
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          pip install ultralytics

      - name: Lint (ruff)
        run: |
          ruff check .

      - name: Run tests
        run: |
          pytest -q
